spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:vigilsense
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
