CREATE TABLE sites (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    location_label  VARCHAR(500),
    latitude        NUMERIC(10, 7) NOT NULL,
    longitude       NUMERIC(11, 7) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sites_latitude_range CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT sites_longitude_range CHECK (longitude >= -180 AND longitude <= 180)
);
