CREATE TABLE sensor_profiles (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                       VARCHAR(64) NOT NULL UNIQUE,
    name                       VARCHAR(255) NOT NULL,
    description                VARCHAR(1000),
    manufacturer_scope         VARCHAR(255),
    model_scope                VARCHAR(255),
    profile_version            VARCHAR(32) NOT NULL,
    relevant_weather_factors   VARCHAR(500) NOT NULL,
    active                     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
