CREATE TABLE sensor_parameters (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_profile_id   BIGINT NOT NULL,
    parameter_key       VARCHAR(64) NOT NULL,
    display_name        VARCHAR(255) NOT NULL,
    unit                VARCHAR(32),
    data_type           VARCHAR(32) NOT NULL,
    min_value           NUMERIC(12, 4),
    max_value           NUMERIC(12, 4),
    default_value       NUMERIC(12, 4),
    sort_order          INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_sensor_parameters_profile
        FOREIGN KEY (sensor_profile_id) REFERENCES sensor_profiles (id),
    CONSTRAINT uq_sensor_parameters_profile_key
        UNIQUE (sensor_profile_id, parameter_key)
);
