CREATE TABLE sensors (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id             BIGINT NOT NULL,
    sensor_profile_id   BIGINT NOT NULL,
    name                VARCHAR(255) NOT NULL,
    manufacturer        VARCHAR(255),
    model               VARCHAR(255),
    installation_zone   VARCHAR(255),
    status              VARCHAR(32) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensors_site
        FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_sensors_profile
        FOREIGN KEY (sensor_profile_id) REFERENCES sensor_profiles (id),
    CONSTRAINT uq_sensors_site_name
        UNIQUE (site_id, name)
);
