CREATE TABLE sensor_configurations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id       BIGINT NOT NULL,
    parameter_id    BIGINT NOT NULL,
    current_value   NUMERIC(12, 4) NOT NULL,
    captured_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensor_configurations_sensor
        FOREIGN KEY (sensor_id) REFERENCES sensors (id),
    CONSTRAINT fk_sensor_configurations_parameter
        FOREIGN KEY (parameter_id) REFERENCES sensor_parameters (id),
    CONSTRAINT uq_sensor_configurations_sensor_parameter
        UNIQUE (sensor_id, parameter_id)
);
