CREATE TABLE weather_records (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id               BIGINT NOT NULL,
    latitude              NUMERIC(10, 7) NOT NULL,
    longitude             NUMERIC(11, 7) NOT NULL,
    temperature_c         NUMERIC(6, 2),
    humidity_percent      NUMERIC(5, 2),
    rainfall_mm           NUMERIC(8, 2),
    wind_speed_ms         NUMERIC(6, 2),
    wind_gust_ms          NUMERIC(6, 2),
    weather_code          INTEGER,
    storm_condition       BOOLEAN NOT NULL DEFAULT FALSE,
    observed_at           TIMESTAMP WITH TIME ZONE,
    retrieved_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    source                VARCHAR(64) NOT NULL,
    partial               BOOLEAN NOT NULL DEFAULT FALSE,
    missing_variables     VARCHAR(500),
    CONSTRAINT fk_weather_records_site
        FOREIGN KEY (site_id) REFERENCES sites (id)
);

CREATE INDEX idx_weather_records_site_observed
    ON weather_records (site_id, observed_at DESC);
