CREATE TABLE calibration_rules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_profile_id   BIGINT NOT NULL,
    weather_factor      VARCHAR(32) NOT NULL,
    operator            VARCHAR(16) NOT NULL,
    threshold           NUMERIC(12, 4),
    parameter_key       VARCHAR(64) NOT NULL,
    action              VARCHAR(16) NOT NULL,
    target_value        NUMERIC(12, 4),
    adjustment_value    NUMERIC(12, 4),
    priority            INTEGER NOT NULL,
    explanation         VARCHAR(500) NOT NULL,
    rule_version        VARCHAR(32) NOT NULL,
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_calibration_rules_profile
        FOREIGN KEY (sensor_profile_id) REFERENCES sensor_profiles (id)
);

CREATE INDEX idx_calibration_rules_profile
    ON calibration_rules (sensor_profile_id, active);
