CREATE TABLE calibration_recommendations (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id               BIGINT NOT NULL,
    site_id                 BIGINT NOT NULL,
    weather_record_id       BIGINT NOT NULL,
    sensor_profile_id       BIGINT NOT NULL,
    risk_level              VARCHAR(16) NOT NULL,
    affected_parameter      VARCHAR(64),
    current_value           NUMERIC(12, 4),
    recommended_value       NUMERIC(12, 4),
    recommended_min         NUMERIC(12, 4),
    recommended_max         NUMERIC(12, 4),
    action                  VARCHAR(16) NOT NULL,
    reasons                 VARCHAR(2000) NOT NULL,
    profile_version         VARCHAR(32) NOT NULL,
    rule_version            VARCHAR(32) NOT NULL,
    status                  VARCHAR(32) NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_calibration_recommendations_sensor
        FOREIGN KEY (sensor_id) REFERENCES sensors (id),
    CONSTRAINT fk_calibration_recommendations_site
        FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_calibration_recommendations_weather
        FOREIGN KEY (weather_record_id) REFERENCES weather_records (id),
    CONSTRAINT fk_calibration_recommendations_profile
        FOREIGN KEY (sensor_profile_id) REFERENCES sensor_profiles (id)
);

CREATE INDEX idx_calibration_recommendations_sensor_created
    ON calibration_recommendations (sensor_id, created_at DESC);
