package com.vigilsense.ai.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.vigilsense.ai.client.AiClient;
import com.vigilsense.ai.dto.AiCalibrationRequest;
import com.vigilsense.ai.dto.AiCalibrationResponse;

@Service
public class AiRecommendationService {

    private static final Logger log = LoggerFactory.getLogger(AiRecommendationService.class);
    private final AiClient aiClient;

    public AiRecommendationService(AiClient aiClient) {
        this.aiClient = aiClient;
    }

    public AiCalibrationResponse generateExplanation(AiCalibrationRequest request) {
        try {
            return aiClient.generateExplanation(request);
        } catch (Exception e) {
            log.error("AI service failed to generate explanation. Falling back to default reason.", e);
            return new AiCalibrationResponse(
                "Recommendation generated by rule engine.",
                "AI explanation is temporarily unavailable."
            );
        }
    }
}
